

COLUMNS:
 veh_value  : float64
 exposure   : float64
 clm        : int64
 numclaims  : int64
 claimcst0  : float64
 veh_body   : object
 veh_age    : object #int64
 gender     : object
 area       : object
 agecat     : object #int64
 X_OBSTAT_  : object
 

TARGET_COLUMN:
 - gender

DROP_COLUMNS:
 - X_OBSTAT_
 - clm
 - numclaims

# for data transformation

LABL_ENCODING:
 - gender
 - veh_body
 

ORDINAL_ENCODING:
 - area


TRANSFORM_FEATURES:
 - veh_value

NUMERICAL_FEATURES:
 - veh_value
 - exposure
 - claimcst0
  
 