artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "C:/Users/Omar/Desktop/Omar_Files/Python_Analysis/Auto_Insurance/Data_Sets/data_car.csv"
  local_data_file: artifacts/data_ingestion/data.csv


data_validation:
  root_dir: artifacts/data_validation
  data_path: artifacts/data_ingestion/data.csv
  STATUS_FILE: artifacts/data_validation/status.txt



data_transformation:
  root_dir: artifacts/data_transformation  
  data_path: artifacts/data_ingestion/data.csv


training:
  root_dir: artifacts/training
  train_data_arr_path : artifacts/data_transformation/final_train.npy
  test_data_arr_path : artifacts/data_transformation/final_test.npy
  best_model: best_model.joblib 
  best_model_params: artifacts/training/best_params.json


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_arr_path : artifacts/data_transformation/final_test.npy
  model_path: artifacts/training/best_model.joblib
  best_model_metrics: artifacts/model_evaluation/best_model_metrics.json
  
